### ISSUE TITLE
Regular expressions

### ISSUE THREAD

**Issue by zz0rk** [ayoisaiah/f2#20] opened 2022-02-21 18:50 UTC
Does the use of regular expressions require Go to be installed?

$ f2 -f \((.*?)\) -r '-'
bash: syntax error near unexpected token `('

Thank you

**Comment by ayoisaiah** [comment] 2022-02-22 05:46
No, you should enclose the find expression in quotes:

```shell
$ f2 -f '((.*?))' -r '-'
```

**Comment by zz0rk** [comment] 2022-02-22 13:23
Thank you for your reply.

I am trying to match a pair of parenthesis and everything inside it, see

https://github.com/ayoisaiah/f2/wiki/Regular-expressions
\((.*?)\)	Match a pair of parenthesis and everything inside

The above syntax will generate
bash: syntax error near unexpected token `('

Your suggestion from above will generate
f2 -f '((.*?))' -r '-'
 INFO  Failed to match any files

In this case
'Test (some text)' will remain unchanged when the expectation was for it to be changed to
'Test -'

Thank you

**Comment by ayoisaiah** [comment] 2022-02-22 19:37
@zz0rk You need to escape the outer parentheses:

![image](https://user-images.githubusercontent.com/13372163/155206033-91c24bda-75db-4f33-8eba-93b99f844d2c.png)

**Comment by zz0rk** [comment] 2022-02-23 00:20
f2 -f '\((.*?)\)' -r '-'
 INFO  Failed to match any files

I don't know what I am doing wrong here

**Comment by ayoisaiah** [comment] 2022-02-23 00:29
You're not including the backslash:

```shell
$ f2 -f '\((.*?)\)' -r '-'
```

**Comment by zz0rk** [comment] 2022-02-23 04:16
I've been copying and pasting the command directly from your comment into my terminal and also typed it manually. Same result.
![image](https://user-images.githubusercontent.com/18619265/155260487-8b000089-d37b-46bf-a4ed-b925f9d9c104.png)

I have noticed that when I preview this comment the backslash gets removed, so in fact the syntax I've been using was correct, but didn't pay attention that when the comment get's posted the backslash gets removed.

**Comment by ayoisaiah** [comment] 2022-02-23 08:36
@zz0rk That's weird, I'm unable to reproduce. What version of f2 are you using?

**Comment by zz0rk** [comment] 2022-02-23 13:33
I am running a current version of Debian 11. I've tested on a second box and I am getting the same results. I can upgrade to the latest version of F2 later today, but the version I am running right now doesn't work.

![image](https://user-images.githubusercontent.com/18619265/155329503-d1ad34a0-578a-4e64-9603-d64c3c55630b.png)

**Comment by zz0rk** [comment] 2022-02-23 13:43
Curiosity got the better of me... still no dice
![image](https://user-images.githubusercontent.com/18619265/155331123-9516130d-de50-46c1-bf8a-0ed503744166.png)

**Comment by ayoisaiah** [comment] 2022-02-23 13:54
I just tested on Debian 11, same result for me. Are you using bash or some other shell?

![image](https://user-images.githubusercontent.com/13372163/155332821-c0243c03-acda-4c06-ad00-2640781289df.png)

**Comment by zz0rk** [comment] 2022-02-24 00:21
Man, this is weird. I don't have anything fancy.
![image](https://user-images.githubusercontent.com/18619265/155432827-04099599-0247-4c32-a907-c96449e8c087.png)
![image](https://user-images.githubusercontent.com/18619265/155433166-08095143-7f75-459a-8937-358b1dc303c9.png)

**Comment by ayoisaiah** [comment] 2022-06-03 20:04
I'm going to close this issue, because I couldn't reproduce it on of my setups.

**Closed by ayoisaiah** 2022-06-03 20:04 UTC
