### ISSUE TITLE
fails to run on long paths in windows.

### ISSUE THREAD

**Issue by nilsocket** [ayoisaiah/f2#15] opened 2021-08-11 07:18 UTC
Create this Dir:
`C:\My Drive\temploweirdo.com\5.Data Structures and Algorithms\1. Asymptotic Analysis and Insertion Sort, Merge Sort\2.Sorting & Searching  why bother with these simple tasks`
Say `a`.

Create this file in `a`:
`1. Sorting & Searching- why bother with these simple tasks- - Data Structure & Algorithms - Part-2.mp4`

Now running `f2 -f '.*'` in `a`, fails with `Path Not Specified Error`.

Cause of error:
https://github.com/ayoisaiah/f2/blob/822837779d13a704770a78080507ebf0d6497759/src/operation_windows.go#L13-L30

Specifically, `syscall.GetFileAttributes()`, most probably because of long path names.

---

Possible Solutions:
Appending `\\?\` in front of an absolute path. (But you seem to use relative path for `baseDir`)

I'm not sure though, please check once again.
Please make sure that it works with long file names and paths.

Thank you.

**Comment by ayoisaiah** [comment] 2021-08-11 08:26
Thank you for reporting this issue, I've been able to reproduce it. I'll track the cause down and let you know once a fix is available.

**Comment by ayoisaiah** [comment] 2021-08-23 11:23
This has been fixed in the latest release. Your suggestion helped a lot :)

**Closed by ayoisaiah** 2021-08-23 11:23 UTC
Labels: bug, windows
