### ISSUE TITLE
[bug] auto make directory failed (windows os)

### ISSUE THREAD

**Issue by mo-han** [ayoisaiah/f2#6] opened 2021-04-14 04:53 UTC
- a file named as `video file from internet [youtube][id][uploader] - part 2.mp4` in `R:\` (windows drive root path)
- i'd like to rename/move it into a sub folder named `[uploader]`
- the f2 command used was `f2 -f "^(.*(\[.+?\]).*?)$" -r "$2\$1" -x R:\`
- f2 error was `An error occurred while renaming 'R:\video file from internet [youtube][id][uploader] - part 2.mp4' to 'R:\[uploader]\video file from internet [youtube][id][uploader] - part 2.mp4'`
- it did try to rename it with prefix path of parent `R:\[uploader]\`, but this sub folder/directory wasn't there

not sure if it's windows os specific bug
maybe the windows path sep backslash `\` is the cause?

**Comment by ayoisaiah** [comment] 2021-04-14 14:42
I've been able to reproduce your issue. You're right, it's the windows path separator that is causing the issue. A fix will be released shortly

**Comment by ayoisaiah** [comment] 2021-04-14 16:43
@mo-han The issue is fixed now, please upgrade to the [latest release](https://github.com/ayoisaiah/f2/releases/tag/v1.4.0). Thanks.

**Closed by ayoisaiah** 2021-04-14 16:43 UTC
Labels: bug, windows
