### ISSUE TITLE
directories to lowercase not working 

### ISSUE THREAD

**Issue by LordMyschkin** [ayoisaiah/f2#31] opened 2022-10-26 20:48 UTC
The command 
`f2 -D -f '.*.' -r {{tr.lw}}'
` 
does produce a correct preview with all upercase letters changes into lowercases, however, 
`f2 -verbose -x -D -f '.*.' -r {{tr.lw}}'
` 
produces a lot of success messages like "SUCCESS Renamed Ludwig_Hirsch to ludwig_hirsch" but does not change a thing.

the command "mv Ludwig_Hirsch ludwig_hirsch" works nicely - did i find an issue there or am i doing sth wrong?

Version is 1.8.0 on rasbian buster, Filesystem is vfat - maybe that is the culprit?

**Comment by ayoisaiah** [comment] 2022-10-30 11:16
Hi @LordMyschkin, I'm unable to reproduce your issue:

![image](https://user-images.githubusercontent.com/13372163/198875641-ed0443df-47e0-455e-b46f-3c173214534b.png)

**Comment by ayoisaiah** [comment] 2022-11-01 07:09
Hi @LordMyschkin

I've been able to reproduce it on FAT32...and it happens because the filesystem is case insensitive. A fix is already in and will be included in the next release.

ca4c00add67c83434fb321f1189ae9353dbaef6b

**Closed** 2022-11-01 07:09 UTC

**Comment by LordMyschkin** [comment] 2022-12-12 19:51
I don't want to file another report - but after cloning the current master, the syntax does not work at all - maybe I do sth wrong...
![Bildschirm­foto 2022-12-12 um 20 46 55](https://user-images.githubusercontent.com/11705882/207140493-aa3d7f08-b4a4-4aeb-bb81-86dc497ed543.png)
I switched to bullseye in the meanwhile....

**Comment by ayoisaiah** [comment] 2022-12-13 15:07
Hi @LordMyschkin The synax has changed...it's not documented yet but you can use `{.lw}` now
